# Numpy General Functions

In [32]:
import numpy as np
import random

pixel = np.random.randint(1,255,size = (4,4))
pixel

array([[ 51,  21, 175,  29],
       [ 44, 166, 206,  18],
       [184, 249, 104, 175],
       [250, 144,  42,   8]])

In [35]:
pixel.sum(axis = 0)

array([529, 580, 527, 230])

In [37]:
Min = array.min()
print(Min)

1


In [41]:
Max = pixel.max()
print(Max)

250


In [42]:
pixel.sort()
pixel

array([[ 21,  29,  51, 175],
       [ 18,  44, 166, 206],
       [104, 175, 184, 249],
       [  8,  42, 144, 250]])

In [47]:
np.hstack(pixel)

array([ 21,  29,  51, 175,  18,  44, 166, 206, 104, 175, 184, 249,   8,
        42, 144, 250])

In [48]:
np.vstack(pixel)

array([[ 21,  29,  51, 175],
       [ 18,  44, 166, 206],
       [104, 175, 184, 249],
       [  8,  42, 144, 250]])

In [49]:
pixel.sum()

1866

In [52]:
pixel.T

array([[ 21,  18, 104,   8],
       [ 29,  44, 175,  42],
       [ 51, 166, 184, 144],
       [175, 206, 249, 250]])

In [53]:
pixel.transpose()

array([[ 21,  18, 104,   8],
       [ 29,  44, 175,  42],
       [ 51, 166, 184, 144],
       [175, 206, 249, 250]])

In [54]:
np.flip(pixel)

array([[250, 144,  42,   8],
       [249, 184, 175, 104],
       [206, 166,  44,  18],
       [175,  51,  29,  21]])

In [55]:
np.flip(pixel,axis = 0)

array([[  8,  42, 144, 250],
       [104, 175, 184, 249],
       [ 18,  44, 166, 206],
       [ 21,  29,  51, 175]])